services:
  oxish:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: builder
    restart: unless-stopped
    ports:
      - "2222:22"
    volumes:
      - ./work:/home/builder/work
      - ./destdir:/home/builder/destdir
